---
title: "## R Conference Events Explorer"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    smooth_scroll: true
    theme: bootstrap
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(crosstalk)
library(plotly)
library(lubridate)
library(leaflet)
library(wordcloud2)
library(tm)
library(rtweet)
library(wordcloud)
library(DT)

```
Row 
-----------------------------------------------------------------------

### Total Yes RSVP

```{r}
df <- readRDS("R_Events.rds")
df <- do.call(rbind.data.frame, df)
df$days <- day(as.POSIXlt(df$created))

yes_rsvp_count <- sum(as.numeric(df$yes_rsvp_count), na.rm = TRUE)
valueBox(value = yes_rsvp_count,icon = "fa-user-plus",caption = "Total Yes RSVP",color = "green")
```

### Total Waitlist Count
```{r}
waitlist_count <- sum(as.numeric(df$waitlist_count), na.rm = TRUE)
valueBox(value = waitlist_count,icon = "fa-user-plus",caption = "Total Waitlist Count",color = "orange")
```

### Unique Country Count
```{r}
unique_venue_country <- NROW(unique(df$venue_country))
valueBox(value = unique_venue_country,icon = "fa-user-plus",caption = "Unique Country Count",color = "coral")
```


Row {data-height=650}
-----------------------------------------------------------------------

### CrossTalk with plotly

```{r}
df <- readRDS("R_Events.rds")
df <- do.call(rbind.data.frame, df)
df$days <- day(as.POSIXlt(df$created))

#Replace us with US
df$venue_country[df$venue_country=="us"]<-"US"

# Wrap data frame in SharedData
sd <- SharedData$new(df)

# Create a filter input
filter_slider("time", "Time", sd, column=~days, round = TRUE)

# Use SharedData like a dataframe with Crosstalk-enabled widgets
 plot_ly(
   data = sd,
  x=~venue_country,
  height = "100px",
  color = I("black")
) %>%
   layout(
     paper_bgcolor = 'transparent',
     plot_bgcolor = "transparent",
        xaxis = list(
          title = "Country",
          color = '#000000',
          zeroline = TRUE,
          showline = TRUE,
          showticklabels = TRUE,
          showgrid = FALSE
        ),
        yaxis = list(
          title = "Freq",
          color = '#000000',
          showticklabels = TRUE,
          showgrid = FALSE
        )
   )

```

### WordCloud

```{r}
#Create a vector containing only the text
data <- rtweet::read_twitter_csv('tweets_database.csv')

text <- data$text
# Create a corpus  
docs <- Corpus(VectorSource(text))
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)

wordcloud(words = df$word, freq = df$freq, min.freq = 1, max.words=200, random.order=FALSE, rot.per=0.35, colors=brewer.pal(8, "Dark2"))
```

Row 
-----------------------------------------------------------------------

### Leaflet

```{r}
df <- readRDS("R_Events.rds")
df <- do.call(rbind.data.frame, df)
m <- leaflet() %>% addProviderTiles(providers$Stamen.Toner) %>%
  addMarkers(df$venue_lon, df$venue_lat, popup = df$venue_address_1, label =df$name,  clusterOptions = markerClusterOptions())
m
```

Row 
-----------------------------------------------------------------------

### DataTable

```{r}
df <- readRDS("R_Events.rds")
df <- do.call(rbind.data.frame, df)
DT::datatable(
  df,
  filter = 'top',
        extensions = c('Buttons', "ColReorder", "Scroller"), #'Select', 'SearchPanes'
        options = list(
          scrollX = TRUE,
          dom = "Bfrtip",#'Pfrtip',
          buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
          colReorder = TRUE,
          deferRender = TRUE,
          scrollY = 500,
          scrollX = 1000,
          scroller = TRUE
        ),
        style = "bootstrap"
)
```